routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ConductorController;
use App\Http\Controllers\VehicleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/conductors', [ConductorController::class, 'index']);
Route::get('/vehicles', [VehicleController::class, 'index'])->name('vehicles.index');





Route::get('/conductors/create', [ConductorController::class, 'create'])->name('conductors.create');
Route::post('/conductors', [ConductorController::class, 'store'])->name('conductors.store');


Route::resource('conductors', ConductorController::class);

Route::get('/conductors/{id}/edit', 'ConductorController@edit')->name('conductors.edit');

Route::get('/conductors/{id}', 'ConductorController@show')->name('conductors.show');

Route::get('/conductors/search', 'ConductorController@search')->name('conductors.search');

Route::get('/vehicles/create', [VehicleController::class, 'create'])->name('vehicles.create');

Route::post('/vehicles', [VehicleController::class, 'store'])->name('vehicles.store');

Route::delete('/vehicles/{id}', [VehicleController::class, 'destroy'])->name('vehicles.destroy');

Route::get('/vehicles/{id}/edit', [VehicleController::class, 'edit'])->name('vehicles.edit');

Route::put('/vehicles/{id}', [VehicleController::class, 'update'])->name('vehicles.update');

Route::get('/vehicles/{id}', [VehicleController::class, 'show'])->name('vehicles.show');

Route::get('/vehicles/search', [VehicleController::class, 'search'])->name('vehicles.search');

app/Models/conductor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class conductor extends Model
{
    use HasFactory;
    protected $fillable = ['nombre', 'telefono', 'correo'];
}

app/Http/Controllers/ConductorController.php
<?php

namespace App\Http\Controllers;

use App\Models\conductor;
use Illuminate\Http\Request;

class ConductorController extends Controller
{
    
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $conductors = Conductor::all(); // Obtiene todos los conductores de la tabla "conductors".
    return view('conductors', compact('conductors'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('conductors.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre' => 'required|string|max:255',
            'telefono' => 'required|string|max:255',
            'correo' => 'required|email',

            // Agrega otras reglas de validación según tus campos
        ]);
    
        // Crea un nuevo objeto Conductor con los datos del formulario
        $conductor = new Conductor();
        $conductor->nombre = $request->input('nombre');
        $conductor->telefono = $request->input('telefono');
        $conductor->correo = $request->input('correo');

        // Asigna otros campos según sea necesario
    
        // Guarda el nuevo conductor en la base de datos
        $conductor->save();
    
        // Redirige a la página de listado de conductores u otra acción
        return redirect('/conductors')->with('success', 'Conductor creado exitosamente.');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $conductor = Conductor::findOrFail($id);
    return view('conductors.show', compact('conductor'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $conductor = Conductor::findOrFail($id);
        return view('conductors.edit', compact('conductor'));

    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $conductor = Conductor::findOrFail($id);
    $conductor->update($request->all());
    return redirect('/conductors')->with('success', 'Conductor eliminado exitosamente.');

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $conductor = Conductor::findOrFail($id);
    $conductor->delete();
    return redirect('/conductors')->with('success', 'Conductor eliminado exitosamente.');

    }


    public function search(Request $request)
{
    $searchTerm = $request->input('search');
    $conductors = Conductor::where('nombre', 'LIKE', "%$searchTerm%")->get();

    if ($request->ajax()) {
        return view('conductors.partial.list', compact('conductors'));
    }

    // Si no es una solicitud AJAX, puedes redirigir o mostrar una vista completa según tus necesidades.
}


}

resources/views/conductors/create.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Crear Nuevo Conductor</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 p-8">
    <h1 class="text-3xl font-bold mb-4">Crear Nuevo Conductor</h1>

    <form action="{{ route('conductors.store') }}" method="POST" class="max-w-md bg-white p-6 rounded-lg shadow-lg">
        @csrf
        <!-- Campos del formulario -->
        <div class="mb-4">
            <label for="nombre" class="block text-gray-700 font-semibold">Nombre:</label>
            <input type="text" name="nombre" id="nombre" class="border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" required>
        </div>

        <div class="mb-4">
            <label for="telefono" class="block text-gray-700 font-semibold">Teléfono:</label>
            <input type="text" name="telefono" id="telefono" class="border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" required>
        </div>

        <div class="mb-6">
            <label for="correo" class="block text-gray-700 font-semibold">Correo:</label>
            <input type="text" name="correo" id="correo" class="border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" required>
        </div>

        <!-- Otros campos -->

        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Guardar</button>
    </form>
</body>
</html>

resources/views/conductors/edit.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Editar Conductor</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 p-8">
    <h1 class="text-3xl font-bold mb-4">Editar Conductor</h1>

    <div class="bg-white p-6 rounded-lg shadow-lg">
        <form action="{{ route('conductors.update', $conductor->id) }}" method="POST">
            @csrf
            @method('PUT')
            <!-- Campos del formulario -->
            <div class="mb-4">
                <label for="nombre" class="block text-gray-700 font-semibold">Nombre:</label>
                <input type="text" name="nombre" id="nombre" class="border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="{{ $conductor->nombre }}" required>
            </div>

            <div class="mb-4">
                <label for="telefono" class="block text-gray-700 font-semibold">Teléfono:</label>
                <input type="text" name="telefono" id="telefono" class="border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="{{ $conductor->telefono }}" required>
            </div>

            <div class="mb-6">
                <label for="correo" class="block text-gray-700 font-semibold">Correo:</label>
                <input type="text" name="correo" id="correo" class="border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="{{ $conductor->correo }}" required>
            </div>


            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Guardar Cambios</button>
        </form>
    </div>
</body>
</html>

resources/views/conductors/show.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Detalles del Conductor</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 p-8">
    <h1 class="text-3xl font-bold mb-4">Detalles del Conductor</h1>

    <div class="bg-white p-6 rounded-lg shadow-lg">
        <p class="mb-4"><strong>ID:</strong> {{ $conductor->id }}</p>
        <p class="mb-4"><strong>Nombre:</strong> {{ $conductor->nombre }}</p>
        <p class="mb-4"><strong>Teléfono:</strong> {{ $conductor->telefono }}</p>
        <p class="mb-4"><strong>Correo:</strong> {{ $conductor->correo }}</p>
      

        <a href="{{ route('conductors.index') }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline inline-block">Volver</a>
    </div>
</body>
</html>